"""Canonical intent synonyms used by the local engine."""

SYNONYMS: dict[str, list[str]] = {
    "extract": ["unpack", "decompress", "unzip", "untar", "unwrap", "expand"],
    "compress": ["zip", "pack", "bundle", "archive", "shrink", "gzip"],
    "list": ["show", "display", "view", "enumerate", "inspect", "print"],
    "search": ["find", "locate", "look for", "grep", "query", "scan"],
    "kill": ["stop", "terminate", "end", "close", "quit", "shutdown"],
    "start": ["launch", "run", "open", "enable", "bring up"],
    "stop": ["halt", "disable", "turn off", "bring down"],
    "restart": ["reload", "bounce", "restart service", "cycle"],
    "status": ["state", "health", "info", "check", "what is running"],
    "install": ["add", "get", "fetch", "setup", "install package"],
    "update": ["refresh", "sync", "upgrade metadata", "pull updates"],
    "upgrade": ["upgrade", "update packages", "bump"],
    "remove": ["delete", "uninstall", "erase", "rm", "purge"],
    "copy": ["duplicate", "clone", "replicate", "mirror"],
    "move": ["rename", "relocate", "shift"],
    "permissions": ["chmod", "access", "rights", "ownership", "acl"],
    "network": ["port", "socket", "ip", "interface", "connection"],
    "disk": ["space", "storage", "filesystem", "mount", "drive"],
    "process": ["pid", "task", "job", "service", "daemon"],
    "monitor": ["watch", "follow", "tail", "stream", "observe"],
    "git": ["commit", "branch", "merge", "stash", "clone", "diff"],
    "download": ["fetch", "save", "curl", "wget", "pull"],
    "upload": ["push", "send", "copy up"],
    "convert": ["transform", "translate", "reformat"],
    "create": ["make", "new", "generate", "touch"],
    "run": ["execute", "launch", "start", "invoke"],
}
